classDiagram
    class Animal {
        +void fazerSom()
    }

    class Gato {
        +void fazerSom()
    }

    class Cachorro {
        +void fazerSom()
    }

    Animal <|-- Gato
    Animal <|-- Cachorro
